### ISSUE TITLE
Cannot use command shortcuts with alt

### ISSUE THREAD

**Issue by Polygons1** [face-hh/fextify#22]
I am using macOS and in macOS the option key is the replacement for the alt key, but it's not working to me

**Comment by Polygons1** [comment]
I saw the problem, and the key (e.key) is ß

**Comment by face-hh** [comment]
(Hopefully) fixed in 6932f48

**Comment by Polygons1** [comment]
@face-hh note, it's just for the s key

**Comment by Polygons1** [comment]
btw @face-hh, it's still not working. just change it to e.code === "KeyS"

**Comment by face-hh** [comment]
> btw @face-hh, it's still not working. just change it to e.code === "KeyS"

could you try modifying it & open a PR so I don't have to blindly test solutions?
